{
 "title": "RBSDCOM/UPS GRAPH GENERATOR A",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"font-size: 35px;\n\t\t\ttext-align: center;\n\t\t\tfont-family: Arial;\n\t\t  border-radius: 10px 200px;\n\t\t\tbackground-image: linear-gradient(314deg,#E6E6E6 20%,  #02DE72 74%);\n\t\t\tcolor:black;\n\"> GENERATOR A - GENERAL</div>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "options": {
    "content": "<img src=/public/img/RBSDCOMIMG/RBSDCOM_555x191.png>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "RBSDCOM /UPS" },
     "host": { "filter": "RBSDCOM - GENERATOR PWY100 - B" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Engine Speed RPM",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 4, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "RBSDCOM /UPS" },
     "host": { "filter": "RBSDCOM - GENERATOR PWY100 - A" },
     "item": { "filter": "Engine Speed RPM" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "FUEL %",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "RBSDCOM /UPS" },
     "host": { "filter": "RBSDCOM - GENERATOR PWY100 - A" },
     "item": { "filter": "FUEL %" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Charge Alternator V",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "RBSDCOM /UPS" },
     "host": { "filter": "RBSDCOM - GENERATOR PWY100 - A" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "Generator: Amper" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Charge Alternator V",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "RBSDCOM /UPS" },
     "host": { "filter": "RBSDCOM - GENERATOR PWY100 - A" },
     "item": { "filter": "Charge Alternator V" },
     "itemTag": { "filter": "Engine: Charge" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 7 },
   "options": {
    "content": "<img src=/public/img/RBSDCOMIMG/generator.png>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "RBSDCOM /UPS" },
     "host": { "filter": "RBSDCOM - GENERATOR PWY100 - B" },
     "item": { "filter": "Engine Starts" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 14 },
   "options": {
    "content": "<div style=\"font-size: 35px;\n\t\t\ttext-align: center;\n\t\t\tfont-family: Arial;\n\t\t  border-radius: 10px 200px;\n\t\t\tbackground-image: linear-gradient(314deg,#E6E6E6 20%,  #02DE72 74%);\n\t\t\tcolor:black;\n\">GENERATOR A - MAIN</div>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 14 },
   "options": {
    "content": "<div style=\"font-size: 35px;\n\t\t\ttext-align: center;\n\t\t\tfont-family: Arial;\n\t\t  border-radius: 10px 200px;\n\t\t\tbackground-image: linear-gradient(314deg,#E6E6E6 20%,  #02DE72 74%);\n\t\t\tcolor:black;\n\">GENERATOR A - GENERATOR</div>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 14 },
   "options": {
    "content": "<div style=\"font-size: 35px;\n\t\t\ttext-align: center;\n\t\t\tfont-family: Arial;\n\t\t  border-radius: 10px 200px;\n\t\t\tbackground-image: linear-gradient(314deg,#E6E6E6 20%,  #02DE72 74%);\n\t\t\tcolor:black;\n\">GENERATOR A - POWER</div>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "RBSDCOM /UPS" },
     "host": { "filter": "RBSDCOM - GENERATOR PWY100 - A" },
     "item": {
      "filter": "Voltage Tree-Phase L1 to L2 (Mains)"
     },
     "itemTag": { "filter": "Main: Voltage" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "RBSDCOM /UPS" },
     "host": { "filter": "RBSDCOM - GENERATOR PWY100 - A" },
     "item": {
      "filter": "Voltage Tree-Phase L2 to L3 (Mains)"
     },
     "itemTag": { "filter": "Main: Voltage" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "RBSDCOM /UPS" },
     "host": { "filter": "RBSDCOM - GENERATOR PWY100 - A" },
     "item": {
      "filter": "Voltage Tree-Phase L2 to L3 (Mains)"
     },
     "itemTag": { "filter": "Main: Voltage" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Generator Voltage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "RBSDCOM /UPS" },
     "host": { "filter": "RBSDCOM - GENERATOR PWY100 - A" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "Generator: Voltage" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Power kVA",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "RBSDCOM /UPS" },
     "host": { "filter": "RBSDCOM - GENERATOR PWY100 - A" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "Power: kVA" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Frequency (Mains)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "RBSDCOM /UPS" },
     "host": { "filter": "RBSDCOM - GENERATOR PWY100 - A" },
     "item": { "filter": "Frequency (Mains)" },
     "itemTag": { "filter": "Main: Frequency" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Frequency Generator",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "mhz" } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "RBSDCOM /UPS" },
     "host": { "filter": "RBSDCOM - GENERATOR PWY100 - A" },
     "item": { "filter": "Frequency (Generator)" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Power kVAr",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "RBSDCOM /UPS" },
     "host": { "filter": "RBSDCOM - GENERATOR PWY100 - A" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "Power: kVAr" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}